# create your drupal and postgres config here, based off the last assignment
services:

  drupal:
    image: custom-drupal
    build: .
    ports:
      - "8088:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes  

  posgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=mypasswd
    ports:
      - "5432:5432"


volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: